/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues in the current workspace */
        get: operations["listIssues"];
        put?: never;
        /** Create a new issue */
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full-text search across issues */
        get: operations["searchIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues grouped by assignee */
        get: operations["listGroupedIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List child issues for multiple parent IDs */
        get: operations["listChildrenByParents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/child-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get child-issue progress for parent IDs */
        get: operations["childIssueProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/quick-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quick-create an issue and dispatch an agent task */
        post: operations["quickCreateIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/preview-trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview which triggers would fire for given issue changes */
        post: operations["previewIssueTrigger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/batch-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update multiple issues at once */
        post: operations["batchUpdateIssues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete multiple issues at once */
        post: operations["batchDeleteIssues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get a single issue */
        get: operations["getIssue"];
        /** Update an issue */
        put: operations["updateIssue"];
        post?: never;
        /** Delete an issue */
        delete: operations["deleteIssue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List comments on an issue */
        get: operations["listComments"];
        put?: never;
        /** Create a comment on an issue */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/comments/trigger-preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview which agents would be triggered by a comment */
        post: operations["previewCommentTriggers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List timeline entries for an issue */
        get: operations["listTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/subscribers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List subscribers for an issue */
        get: operations["listIssueSubscribers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe a user to an issue */
        post: operations["subscribeToIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsubscribe a user from an issue */
        post: operations["unsubscribeFromIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/active-task": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get the active task for an issue */
        get: operations["getActiveTaskForIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a task on an issue */
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run an issue's agent task */
        post: operations["rerunIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/task-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List task runs for an issue */
        get: operations["listTasksByIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get token usage for an issue */
        get: operations["getIssueUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reaction to an issue */
        post: operations["addIssueReaction"];
        /** Remove a reaction from an issue */
        delete: operations["removeIssueReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List attachments for an issue */
        get: operations["listAttachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List child issues */
        get: operations["listChildIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List labels attached to an issue */
        get: operations["listLabelsForIssue"];
        put?: never;
        /** Attach a label to an issue */
        post: operations["attachLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                labelId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach a label from an issue */
        delete: operations["detachLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List metadata key-value pairs for an issue */
        get: operations["listIssueMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/metadata/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Set a metadata key on an issue */
        put: operations["setIssueMetadataKey"];
        post?: never;
        /** Delete a metadata key from an issue */
        delete: operations["deleteIssueMetadataKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** List GitHub pull requests linked to an issue */
        get: operations["listPullRequestsForIssue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{id}/squad-evaluated": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a squad leader evaluation outcome */
        post: operations["recordSquadLeaderEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a comment */
        put: operations["updateComment"];
        post?: never;
        /** Delete a comment */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a comment */
        post: operations["resolveComment"];
        /** Unresolve a comment */
        delete: operations["unresolveComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a reaction to a comment */
        post: operations["addReaction"];
        /** Remove a reaction from a comment */
        delete: operations["removeReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents in the current workspace */
        get: operations["listAgents"];
        put?: never;
        /** Create a new agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/from-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an agent from a template */
        post: operations["createAgentFromTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** Get a single agent */
        get: operations["getAgent"];
        /** Update an agent */
        put: operations["updateAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an agent */
        post: operations["archiveAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived agent */
        post: operations["restoreAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/cancel-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel all active tasks for an agent */
        post: operations["cancelAgentTasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** List tasks for an agent */
        get: operations["listAgentTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/skills": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** List skills attached to an agent */
        get: operations["listAgentSkills"];
        /** Replace the full set of skills attached to an agent */
        put: operations["setAgentSkills"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/skills/add": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add skills to an agent (idempotent) */
        post: operations["addAgentSkills"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/env": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** Get custom environment variables for an agent */
        get: operations["getAgentEnv"];
        /** Update custom environment variables for an agent */
        put: operations["updateAgentEnv"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List squads in the current workspace */
        get: operations["listSquads"];
        put?: never;
        /** Create a new squad */
        post: operations["createSquad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        /** Get a single squad */
        get: operations["getSquad"];
        /** Update a squad */
        put: operations["updateSquad"];
        post?: never;
        /** Delete a squad */
        delete: operations["deleteSquad"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squads/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        /** List members of a squad */
        get: operations["listSquadMembers"];
        put?: never;
        /** Add a member to a squad */
        post: operations["addSquadMember"];
        /** Remove a member from a squad */
        delete: operations["removeSquadMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squads/{id}/members/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        /** List squad members with presence/status info */
        get: operations["listSquadMemberStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squads/{id}/members/role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a squad member's role */
        patch: operations["updateSquadMemberRole"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        IssueResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            number: number;
            identifier: string;
            title: string;
            description?: string | null;
            status: string;
            priority: string;
            assignee_type?: string | null;
            assignee_id?: string | null;
            creator_type: string;
            /** Format: uuid */
            creator_id: string;
            parent_issue_id?: string | null;
            project_id?: string | null;
            position: number;
            stage?: number | null;
            start_date?: string | null;
            due_date?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            metadata: {
                [key: string]: unknown;
            };
            reactions?: components["schemas"]["IssueReactionResponse"][];
            attachments?: components["schemas"]["AttachmentResponse"][];
            labels?: components["schemas"]["LabelResponse"][];
        };
        SearchIssueResponse: components["schemas"]["IssueResponse"] & {
            match_source: string;
            matched_snippet?: string | null;
            matched_description_snippet?: string | null;
            matched_comment_snippet?: string | null;
        };
        GroupedIssuesResponse: {
            groups: components["schemas"]["IssueAssigneeGroupResponse"][];
        };
        IssueAssigneeGroupResponse: {
            assignee_type?: string | null;
            assignee_id?: string | null;
            total: number;
            issues: components["schemas"]["IssueResponse"][];
        };
        CreateIssueRequest: {
            title: string;
            description?: string | null;
            status?: string;
            priority?: string;
            assignee_type?: string | null;
            assignee_id?: string | null;
            parent_issue_id?: string | null;
            project_id?: string | null;
            stage?: number | null;
            start_date?: string | null;
            due_date?: string | null;
            attachment_ids?: string[];
            origin_type?: string | null;
            origin_id?: string | null;
            allow_duplicate?: boolean;
        };
        UpdateIssueRequest: {
            title?: string | null;
            description?: string | null;
            status?: string | null;
            priority?: string | null;
            assignee_type?: string | null;
            assignee_id?: string | null;
            position?: number | null;
            start_date?: string | null;
            due_date?: string | null;
            parent_issue_id?: string | null;
            project_id?: string | null;
            stage?: number | null;
            attachment_ids?: string[];
            suppress_run?: boolean;
            handoff_note?: string;
        };
        QuickCreateIssueRequest: {
            agent_id?: string;
            squad_id?: string;
            prompt: string;
            project_id?: string;
            parent_issue_id?: string;
            attachment_ids?: string[];
        };
        QuickCreateIssueResponse: {
            /** Format: uuid */
            task_id: string;
            issue?: components["schemas"]["IssueResponse"];
        };
        BatchUpdateIssuesRequest: {
            issue_ids: string[];
            updates: components["schemas"]["UpdateIssueRequest"];
        };
        BatchDeleteIssuesRequest: {
            issue_ids: string[];
        };
        IssueTriggerPreviewRequest: {
            issue_ids?: string[];
            is_create?: boolean;
            assignee_type?: string;
            assignee_id?: string;
            status?: string;
        };
        IssueTriggerPreviewResponse: {
            triggers: components["schemas"]["IssueTriggerPreviewItem"][];
            total_count: number;
        };
        IssueTriggerPreviewItem: {
            issue_id?: string;
            agent_id?: string;
            agent_name?: string;
            trigger_source?: string;
        };
        RerunIssueRequest: {
            task_id?: string;
        };
        SetIssueMetadataKeyRequest: {
            value: unknown;
        };
        AttachLabelRequest: {
            /** Format: uuid */
            label_id: string;
        };
        IssueReactionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            issue_id: string;
            actor_type: string;
            /** Format: uuid */
            actor_id: string;
            emoji: string;
            /** Format: date-time */
            created_at: string;
        };
        SubscriberResponse: {
            /** Format: uuid */
            issue_id: string;
            user_type: string;
            /** Format: uuid */
            user_id: string;
            reason: string;
            /** Format: date-time */
            created_at: string;
        };
        LabelResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            name: string;
            color: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AttachmentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            issue_id?: string | null;
            comment_id?: string | null;
            chat_session_id?: string | null;
            chat_message_id?: string | null;
            uploader_type: string;
            /** Format: uuid */
            uploader_id: string;
            filename: string;
            content_type: string;
            size: number;
            /** Format: date-time */
            created_at: string;
        };
        CommentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            issue_id: string;
            author_type: string;
            /** Format: uuid */
            author_id: string;
            content: string;
            type: string;
            parent_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            resolved_at?: string | null;
            resolved_by_type?: string | null;
            resolved_by_id?: string | null;
            source_task_id?: string | null;
            reactions: components["schemas"]["ReactionResponse"][];
            attachments: components["schemas"]["AttachmentResponse"][];
            reply_count?: number | null;
            last_activity_at?: string | null;
            content_truncated?: boolean | null;
        };
        CreateCommentRequest: {
            content: string;
            type: string;
            parent_id?: string | null;
            attachment_ids?: string[];
            suppress_agent_ids?: string[];
        };
        UpdateCommentRequest: {
            content?: string;
            attachment_ids?: string[];
            suppress_agent_ids?: string[];
        };
        CommentTriggerPreviewRequest: {
            content: string;
            parent_id?: string | null;
            editing_comment_id?: string | null;
        };
        CommentTriggerPreviewResponse: {
            agents: components["schemas"]["CommentTriggerAgentResponse"][];
        };
        CommentTriggerAgentResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            avatar_url?: string | null;
            source: string;
            reason: string;
        };
        ReactionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            comment_id: string;
            actor_type: string;
            /** Format: uuid */
            actor_id: string;
            emoji: string;
            /** Format: date-time */
            created_at: string;
        };
        AgentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            /** Format: uuid */
            runtime_id: string;
            name: string;
            description: string;
            instructions: string;
            avatar_url?: string | null;
            runtime_mode: string;
            runtime_config: unknown;
            custom_args: string[];
            mcp_config: unknown;
            has_custom_env: boolean;
            custom_env_key_count: number;
            mcp_config_redacted: boolean;
            visibility: string;
            status: string;
            max_concurrent_tasks: number;
            model: string;
            thinking_level: string;
            owner_id?: string | null;
            skills: components["schemas"]["AgentSkillSummary"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            archived_at?: string | null;
            archived_by?: string | null;
        };
        CreateAgentRequest: {
            name: string;
            description?: string;
            instructions?: string;
            avatar_url?: string | null;
            /** Format: uuid */
            runtime_id: string;
            runtime_config?: unknown;
            custom_env?: {
                [key: string]: string;
            };
            custom_args?: string[];
            mcp_config?: unknown;
            visibility?: string;
            max_concurrent_tasks?: number;
            model: string;
            thinking_level?: string;
            template?: string;
        };
        UpdateAgentRequest: {
            name?: string | null;
            description?: string | null;
            instructions?: string | null;
            avatar_url?: string | null;
            runtime_id?: string | null;
            runtime_config?: unknown;
            custom_args?: string[];
            mcp_config?: unknown;
            visibility?: string | null;
            status?: string | null;
            max_concurrent_tasks?: number | null;
            model?: string | null;
            thinking_level?: string | null;
        };
        CreateAgentFromTemplateRequest: {
            template_slug: string;
            name: string;
            /** Format: uuid */
            runtime_id: string;
            model?: string;
            visibility?: string;
            max_concurrent_tasks?: number;
            description?: string | null;
            instructions?: string | null;
            avatar_url?: string | null;
            extra_skill_ids?: string[];
        };
        AgentSkillSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
        };
        SkillSummaryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            name: string;
            description: string;
            config: unknown;
            created_by?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SetAgentSkillsRequest: {
            skill_ids: string[];
        };
        AddAgentSkillsRequest: {
            skill_ids: string[];
        };
        AgentEnvResponse: {
            /** Format: uuid */
            agent_id: string;
            custom_env: {
                [key: string]: string;
            };
        };
        UpdateAgentEnvRequest: {
            custom_env: {
                [key: string]: string;
            };
        };
        AgentTaskResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agent_id: string;
            /** Format: uuid */
            runtime_id: string;
            /** Format: uuid */
            issue_id?: string | null;
            /** Format: uuid */
            workspace_id: string;
            workspace_context?: string;
            thread_name?: string;
            status: string;
            priority: string;
            /** Format: date-time */
            dispatched_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            result?: string | null;
            error?: string | null;
            failure_reason?: string | null;
            attempt: number;
            max_attempts: number;
            parent_task_id?: string | null;
            agent?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                avatar_url?: string | null;
            };
            repos?: {
                [key: string]: unknown;
            }[];
            project_id?: string | null;
            project_title?: string | null;
            project_description?: string | null;
            project_resources?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            created_at: string;
        };
        SquadResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            name: string;
            description: string;
            instructions: string;
            avatar_url?: string | null;
            /** Format: uuid */
            leader_id: string;
            /** Format: uuid */
            creator_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            archived_at?: string | null;
            archived_by?: string | null;
            member_count: number;
            member_preview: components["schemas"]["SquadMemberPreviewResponse"][];
        };
        CreateSquadRequest: {
            name: string;
            description?: string;
            /** Format: uuid */
            leader_id?: string;
            avatar_url?: string | null;
        };
        UpdateSquadRequest: {
            name?: string;
            description?: string;
            instructions?: string;
            /** Format: uuid */
            leader_id?: string;
            avatar_url?: string | null;
        };
        SquadMemberPreviewResponse: {
            member_type: string;
            /** Format: uuid */
            member_id: string;
            role: string;
        };
        SquadMemberResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            squad_id: string;
            member_type: string;
            /** Format: uuid */
            member_id: string;
            role: string;
            /** Format: date-time */
            created_at: string;
        };
        AddSquadMemberRequest: {
            member_type: string;
            /** Format: uuid */
            member_id: string;
            role: string;
        };
        UpdateSquadMemberRoleRequest: {
            member_type: string;
            /** Format: uuid */
            member_id: string;
            role: string;
        };
        SquadMemberStatusResponse: {
            member_type: string;
            /** Format: uuid */
            member_id: string;
            status?: string | null;
            active_issues: components["schemas"]["SquadActiveIssueBrief"][];
            last_active_at?: string | null;
        };
        SquadActiveIssueBrief: {
            /** Format: uuid */
            issue_id: string;
            identifier: string;
            title: string;
            issue_status: string;
        };
        SquadMemberStatusListResponse: {
            members: components["schemas"]["SquadMemberStatusResponse"][];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IssueId: string;
        CommentId: string;
        AgentId: string;
        SquadId: string;
        StatusFilter: string;
        AssigneeFilter: string;
        SearchFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIssues: {
        parameters: {
            query?: {
                status?: components["parameters"]["StatusFilter"];
                assignee_id?: components["parameters"]["AssigneeFilter"];
                search?: components["parameters"]["SearchFilter"];
                parent_issue_id?: string;
                project_id?: string;
                label_id?: string;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"][];
                };
            };
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequest"];
            };
        };
        responses: {
            /** @description Created issue */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            /** @description Duplicate issue detected */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchIssues: {
        parameters: {
            query: {
                q: string;
                status?: components["parameters"]["StatusFilter"];
                assignee_id?: components["parameters"]["AssigneeFilter"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchIssueResponse"][];
                };
            };
        };
    };
    listGroupedIssues: {
        parameters: {
            query?: {
                status?: components["parameters"]["StatusFilter"];
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupedIssuesResponse"];
                };
            };
        };
    };
    listChildrenByParents: {
        parameters: {
            query: {
                parent_ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"][];
                };
            };
        };
    };
    childIssueProgress: {
        parameters: {
            query: {
                parent_ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    quickCreateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickCreateIssueRequest"];
            };
        };
        responses: {
            /** @description Quick-create result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickCreateIssueResponse"];
                };
            };
        };
    };
    previewIssueTrigger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueTriggerPreviewRequest"];
            };
        };
        responses: {
            /** @description Trigger preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueTriggerPreviewResponse"];
                };
            };
        };
    };
    batchUpdateIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdateIssuesRequest"];
            };
        };
        responses: {
            /** @description Batch update result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        updated?: number;
                    };
                };
            };
        };
    };
    batchDeleteIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteIssuesRequest"];
            };
        };
        responses: {
            /** @description Batch delete result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deleted?: number;
                    };
                };
            };
        };
    };
    getIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequest"];
            };
        };
        responses: {
            /** @description Updated issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: {
                parent_id?: string;
                roots_only?: boolean;
                summary?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"][];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Created comment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    previewCommentTriggers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentTriggerPreviewRequest"];
            };
        };
        responses: {
            /** @description Trigger preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentTriggerPreviewResponse"];
                };
            };
        };
    };
    listTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    listIssueSubscribers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriber list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriberResponse"][];
                };
            };
        };
    };
    subscribeToIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_id: string;
                    user_type: string;
                };
            };
        };
        responses: {
            /** @description Already subscribed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscribed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsubscribeFromIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_id: string;
                    user_type: string;
                };
            };
        };
        responses: {
            /** @description Unsubscribed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActiveTaskForIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tasks?: components["schemas"]["AgentTaskResponse"][];
                    };
                };
            };
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rerunIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunIssueRequest"];
            };
        };
        responses: {
            /** @description Re-run started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTasksByIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTaskResponse"][];
                };
            };
        };
    };
    getIssueUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    addIssueReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    emoji: string;
                };
            };
        };
        responses: {
            /** @description Reaction added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueReactionResponse"];
                };
            };
        };
    };
    removeIssueReaction: {
        parameters: {
            query: {
                emoji: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponse"][];
                };
            };
        };
    };
    listChildIssues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Child issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueResponse"][];
                };
            };
        };
    };
    listLabelsForIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"][];
                };
            };
        };
    };
    attachLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachLabelRequest"];
            };
        };
        responses: {
            /** @description Label attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
        };
    };
    detachLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIssueMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    setIssueMetadataKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIssueMetadataKeyRequest"];
            };
        };
        responses: {
            /** @description Metadata key set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteIssueMetadataKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPullRequestsForIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pull requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pull_requests?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    recordSquadLeaderEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    outcome: string;
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Updated comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    unresolveComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unresolved comment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    addReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    emoji: string;
                };
            };
        };
        responses: {
            /** @description Reaction added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReactionResponse"];
                };
            };
        };
    };
    removeReaction: {
        parameters: {
            query: {
                emoji: string;
            };
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                include_archived?: boolean;
                runtime_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"][];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Created agent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    createAgentFromTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentFromTemplateRequest"];
            };
        };
        responses: {
            /** @description Created agent from template */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Updated agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    restoreAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    cancelAgentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cancelled?: number;
                    };
                };
            };
        };
    };
    listAgentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTaskResponse"][];
                };
            };
        };
    };
    listAgentSkills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSummaryResponse"][];
                };
            };
        };
    };
    setAgentSkills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAgentSkillsRequest"];
            };
        };
        responses: {
            /** @description Skills set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addAgentSkills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAgentSkillsRequest"];
            };
        };
        responses: {
            /** @description Skills added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAgentEnv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent env */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnvResponse"];
                };
            };
        };
    };
    updateAgentEnv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentEnvRequest"];
            };
        };
        responses: {
            /** @description Updated agent env */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnvResponse"];
                };
            };
        };
    };
    listSquads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Squad list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadResponse"][];
                };
            };
        };
    };
    createSquad: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSquadRequest"];
            };
        };
        responses: {
            /** @description Created squad */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadResponse"];
                };
            };
        };
    };
    getSquad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Squad detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSquad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSquadRequest"];
            };
        };
        responses: {
            /** @description Updated squad */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSquad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSquadMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberResponse"][];
                };
            };
        };
    };
    addSquadMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSquadMemberRequest"];
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberResponse"];
                };
            };
        };
    };
    removeSquadMember: {
        parameters: {
            query: {
                member_type: string;
                member_id: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSquadMemberStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member status list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberStatusListResponse"];
                };
            };
        };
    };
    updateSquadMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SquadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSquadMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadMemberResponse"];
                };
            };
        };
    };
}
